#!/usr/bin/env bash
# =============================================================
# n8n-ecosystem-unified — Setup Script
# Proxmox LXC / Debian 12 (bookworm) edition
# Based on JazenaYLA/n8n-claw setup.sh
#
# Differences from n8n-claw setup.sh:
#   - Caddy reverse proxy (not Nginx)
#   - Proxmox LXC detection and Docker nesting check
#   - Multi-channel env vars (WhatsApp/Evolution API)
#   - LLM provider selection: OpenRouter OR Anthropic direct
#   - CTI stack env vars (MISP, Wazuh, OpenCTI, TheHive, Cortex)
#   - SearXNG secret key generation
# =============================================================
set -euo pipefail

RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$BASEDIR/.env"

log()  { echo -e "${GREEN}[setup]${RESET} $*"; }
warn() { echo -e "${YELLOW}[warn]${RESET} $*"; }
err()  { echo -e "${RED}[error]${RESET} $*" >&2; }

require_root() {
  if [[ $EUID -ne 0 ]]; then
    err "Run as root: sudo bash setup.sh"
    exit 1
  fi
}

check_proxmox_lxc() {
  if grep -q 'container=lxc' /proc/1/environ 2>/dev/null || [ -f /run/container_type ]; then
    log "Proxmox LXC detected."
    if ! grep -q 'nesting=1' /proc/mounts 2>/dev/null; then
      warn "LXC nesting may not be enabled. If Docker fails, enable nesting in Proxmox: pct set <id> --features nesting=1"
    fi
  fi
}

install_docker() {
  if command -v docker &>/dev/null; then
    log "Docker already installed: $(docker --version)"
    return
  fi
  log "Installing Docker..."
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl gnupg lsb-release
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable docker
  systemctl start docker
  log "Docker installed."
}

install_caddy() {
  if command -v caddy &>/dev/null; then
    log "Caddy already installed."
    return
  fi
  log "Installing Caddy..."
  apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | \
    gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | \
    tee /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
  apt-get install -y -qq caddy
  log "Caddy installed."
}

generate_secrets() {
  log "Generating secrets..."
  N8N_ENCRYPTION_KEY=$(openssl rand -hex 32)
  SUPABASE_JWT_SECRET=$(openssl rand -hex 32)
  SEARXNG_SECRET_KEY=$(openssl rand -hex 32)
  POSTGRES_PASSWORD=$(openssl rand -hex 16)
  log "Secrets generated."
}

generate_jwt_keys() {
  # Generate Supabase anon/service keys from JWT secret
  # These are standard Supabase JWT payloads
  # For production, use supabase CLI: supabase start
  # For homelab self-hosted, these static tokens are acceptable
  HEADER=$(echo -n '{"alg":"HS256","typ":"JWT"}' | base64 -w0 | sed 's/=//g;s/+/-/g;s|/|_|g')
  
  ANON_PAYLOAD=$(echo -n '{"role":"anon","iss":"supabase","iat":1700000000,"exp":2000000000}' | base64 -w0 | sed 's/=//g;s/+/-/g;s|/|_|g')
  SERVICE_PAYLOAD=$(echo -n '{"role":"service_role","iss":"supabase","iat":1700000000,"exp":2000000000}' | base64 -w0 | sed 's/=//g;s/+/-/g;s|/|_|g')

  sign() {
    local payload="$1"
    local data="$HEADER.$payload"
    echo -n "$data" | openssl dgst -sha256 -hmac "$SUPABASE_JWT_SECRET" -binary | base64 -w0 | sed 's/=//g;s/+/-/g;s|/|_|g'
  }

  SUPABASE_ANON_KEY="$HEADER.$ANON_PAYLOAD.$(sign "$ANON_PAYLOAD")"
  SUPABASE_SERVICE_KEY="$HEADER.$SERVICE_PAYLOAD.$(sign "$SERVICE_PAYLOAD")"
}

write_env() {
  log "Writing .env file..."
  cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date)
# DO NOT commit this file

# n8n
N8N_URL=https://${N8N_DOMAIN}
N8N_INTERNAL_URL=http://n8n:5678
N8N_API_KEY=
N8N_HOST=${N8N_DOMAIN}
N8N_PROTOCOL=https
N8N_WEBHOOK_URL=https://${N8N_DOMAIN}
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
TIMEZONE=${TIMEZONE}

# Supabase
SUPABASE_URL=http://kong:8000
SUPABASE_PUBLIC_URL=http://127.0.0.1:8000
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}

# PostgreSQL
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Telegram
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}

# WhatsApp / Evolution API
EVOLUTION_INSTANCE_NAME=${EVOLUTION_INSTANCE_NAME:-}
WHATSAPP_PHONE=${WHATSAPP_PHONE:-}
EVOLUTION_API_URL=${EVOLUTION_API_URL:-}

# LLM
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY:-}

# Credential names (must match workflow JSON)
N8N_CREDENTIAL_ANTHROPIC_NAME=Anthropic API
N8N_CREDENTIAL_OPENROUTER_NAME=OpenRouter
N8N_CREDENTIAL_GOOGLE_NAME=Google AI
N8N_CREDENTIAL_TELEGRAM_NAME=Telegram Bot
N8N_CREDENTIAL_POSTGRES_NAME=Supabase Postgres
N8N_CREDENTIAL_GMAIL_NAME=Gmail
N8N_CREDENTIAL_EVOLUTION_NAME=Evolution API

# Embeddings
EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER:-openai}
EMBEDDING_API_KEY=${EMBEDDING_API_KEY:-}
EMBEDDING_MODEL=text-embedding-3-small

# SearXNG
SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY}

# CTI Stack
MISP_URL=${MISP_URL:-}
MISP_API_KEY=${MISP_API_KEY:-}
WAZUH_URL=${WAZUH_URL:-}
WAZUH_USER=${WAZUH_USER:-admin}
WAZUH_PASSWORD=${WAZUH_PASSWORD:-}
OPENCTI_URL=${OPENCTI_URL:-}
OPENCTI_TOKEN=${OPENCTI_TOKEN:-}
THEHIVE_URL=${THEHIVE_URL:-}
THEHIVE_API_KEY=${THEHIVE_API_KEY:-}
CORTEX_URL=${CORTEX_URL:-}
CORTEX_API_KEY=${CORTEX_API_KEY:-}
EOF
  chmod 600 "$ENV_FILE"
  log ".env written."
}

write_searxng_settings() {
  # Replace {{SEARXNG_SECRET_KEY}} placeholder in searxng/settings.yml
  if [ -f "$BASEDIR/searxng/settings.yml" ]; then
    sed -i "s|{{SEARXNG_SECRET_KEY}}|${SEARXNG_SECRET_KEY}|g" "$BASEDIR/searxng/settings.yml"
    log "SearXNG settings.yml updated with generated secret key."
  fi
}

write_kong_deployed() {
  # Generate supabase/kong.deployed.yml with real keys
  if [ -f "$BASEDIR/supabase/kong.yml" ]; then
    sed "s|{{SUPABASE_ANON_KEY}}|${SUPABASE_ANON_KEY}|g;s|{{SUPABASE_SERVICE_KEY}}|${SUPABASE_SERVICE_KEY}|g" \
      "$BASEDIR/supabase/kong.yml" > "$BASEDIR/supabase/kong.deployed.yml"
    log "supabase/kong.deployed.yml generated."
  fi
}

write_caddyfile() {
  CADDYFILE="/etc/caddy/Caddyfile"
  log "Writing Caddyfile for ${N8N_DOMAIN}..."
  # Backup existing
  [ -f "$CADDYFILE" ] && cp "$CADDYFILE" "${CADDYFILE}.bak.$(date +%s)"
  cat >> "$CADDYFILE" <<EOF

# n8n-ecosystem-unified
${N8N_DOMAIN} {
    reverse_proxy localhost:5678
    encode gzip
    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains"
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
    }
}
EOF
  systemctl reload caddy 2>/dev/null || systemctl restart caddy
  log "Caddy configured for https://${N8N_DOMAIN}"
}

prompt() {
  local var_name="$1"
  local prompt_text="$2"
  local default="${3:-}"
  local secret="${4:-false}"

  if [[ -n "$default" ]]; then
    echo -en "${CYAN}${prompt_text}${RESET} [${default}]: "
  else
    echo -en "${CYAN}${prompt_text}${RESET}: "
  fi

  if [[ "$secret" == "true" ]]; then
    read -rs value
    echo
  else
    read -r value
  fi

  if [[ -z "$value" && -n "$default" ]]; then
    value="$default"
  fi

  printf -v "$var_name" '%s' "$value"
}

collect_inputs() {
  echo -e "\n${BOLD}=== n8n-ecosystem-unified Setup ===${RESET}\n"

  prompt N8N_DOMAIN      "n8n public domain (e.g. n8n.yourdomain.com)" "n8n.yourdomain.com"
  prompt TIMEZONE        "Timezone" "America/Chicago"
  prompt TELEGRAM_BOT_TOKEN  "Telegram Bot Token (@BotFather)" "" true
  prompt TELEGRAM_CHAT_ID    "Telegram Chat ID"

  echo -e "\n${BOLD}--- LLM Providers ---${RESET}"
  prompt OPENROUTER_API_KEY   "OpenRouter API Key (recommended for tiered model routing)" "" true
  prompt ANTHROPIC_API_KEY    "Anthropic API Key (optional if using OpenRouter)" "" true
  prompt GOOGLE_AI_API_KEY    "Google AI API Key (for Gemini Flash media analysis)" "" true

  echo -e "\n${BOLD}--- WhatsApp (optional) ---${RESET}"
  prompt EVOLUTION_INSTANCE_NAME  "Evolution API instance name (leave blank to skip)" ""
  prompt WHATSAPP_PHONE           "WhatsApp phone number (digits only, leave blank to skip)" ""
  prompt EVOLUTION_API_URL        "Evolution API URL (leave blank to skip)" ""

  echo -e "\n${BOLD}--- Embeddings ---${RESET}"
  prompt EMBEDDING_PROVIDER  "Embedding provider (openai/voyage/ollama)" "openai"
  prompt EMBEDDING_API_KEY   "Embedding API Key (leave blank if same as OpenRouter/Anthropic)" "" true

  echo -e "\n${BOLD}--- CTI Stack (optional — leave blank to skip) ---${RESET}"
  prompt MISP_URL      "MISP URL" ""
  prompt MISP_API_KEY  "MISP API Key" "" true
  prompt WAZUH_URL     "Wazuh URL" ""
  prompt WAZUH_USER    "Wazuh user" "admin"
  prompt WAZUH_PASSWORD "Wazuh password" "" true
  prompt OPENCTI_URL   "OpenCTI URL" ""
  prompt OPENCTI_TOKEN "OpenCTI token" "" true
  prompt THEHIVE_URL   "TheHive URL" ""
  prompt THEHIVE_API_KEY "TheHive API key" "" true
  prompt CORTEX_URL    "Cortex URL" ""
  prompt CORTEX_API_KEY "Cortex API key" "" true
}

start_stack() {
  log "Starting Docker stack..."
  cd "$BASEDIR"
  docker compose pull --quiet
  docker compose up -d
  log "Stack started. Waiting for n8n to be ready..."
  local retries=30
  while ! curl -sf http://localhost:5678/healthz &>/dev/null; do
    sleep 3
    retries=$((retries-1))
    if [[ $retries -le 0 ]]; then
      warn "n8n did not respond after 90s. Check: docker compose logs n8n"
      break
    fi
  done
  log "n8n is up."
}

print_next_steps() {
  echo -e "\n${BOLD}${GREEN}=== Setup Complete ===${RESET}\n"
  echo -e "  n8n:           ${CYAN}https://${N8N_DOMAIN}${RESET}"
  echo -e "  Supabase Studio: ${CYAN}http://127.0.0.1:3001${RESET} (SSH tunnel recommended)"
  echo -e "  SearXNG:         ${CYAN}http://127.0.0.1:8888${RESET} (internal only)"
  echo -e ""
  echo -e "${BOLD}Next steps:${RESET}"
  echo -e "  1. Open n8n and complete initial account setup"
  echo -e "  2. Go to Settings → API and generate your N8N_API_KEY"
  echo -e "  3. Update .env with the API key, then: docker compose restart n8n"
  echo -e "  4. Import workflows from workflows/unified/ via n8n UI → Import"
  echo -e "  5. Set n8n Variables: TELEGRAM_CHAT_ID, EVOLUTION_INSTANCE_NAME, WHATSAPP_PHONE"
  echo -e "  6. Create credentials in n8n matching the names in .env.example"
  echo -e ""
  echo -e "${BOLD}Full docs:${RESET} docs/PROXMOX_SETUP.md"
}

main() {
  require_root
  check_proxmox_lxc
  collect_inputs
  generate_secrets
  generate_jwt_keys
  write_env
  write_searxng_settings
  write_kong_deployed
  install_docker
  install_caddy
  write_caddyfile
  start_stack
  print_next_steps
}

main "$@"
